# Generated by Django 4.1.2 on 2022-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer_name', models.CharField(max_length=200)),
                ('platform', models.BooleanField(default=False)),
                ('last_stream', models.DateTimeField(verbose_name='last watched stream')),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
